print("---------------------------------------")
print("Ejercicio2: PROMEDIO DE 3 NOTAS")
print("---------------------------------------")
print("Ingrese las 3 notas del alumno: ")
N1 = int(input("N1: "))
N2 = int(input("N2: "))
N3 = int(input("N3: "))
P = int((N1 + N2+ N3)/3)
print("El promedio es: " , P)